import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :fraud_system, FraudSystemWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :fraud_system, :kafka,
  hosts: [localhost: 9092], # In docker-compose, this should be overridden or use "kafka" host
  group_id: "fraud_system_prod",
  topics: ["transactions"]

# Override for Docker
if System.get_env("KAFKA_HOST") do
  config :fraud_system, :kafka,
    hosts: [String.to_atom(System.get_env("KAFKA_HOST")) || :kafka, 9092]
end

# Hardcode for this docker-compose setup
config :fraud_system, :kafka,
  hosts: "kafka:9092",
  group_id: "fraud_system_prod",
  topics: ["transactions"]
